# Получение списка предложений по аренде
GET http://localhost:3000/offers HTTP/1.1

###
# Создание нового предложения
POST http://localhost:3000/offers HTTP/1.1

###
# Редактирование предложения
PUT http://localhost:3000/offers/1 HTTP/1.1

###
# Удаление предложения
DELETE http://localhost:3000/offers/1 HTTP/1.1

###
# Получение детальной информации о предложении
GET http://localhost:3000/offers/1 HTTP/1.1

###