# Получение списка предложений по аренде
GET http://localhost:3000/offers HTTP/1.1

###
# Создание нового предложения
POST http://localhost:3000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Годрикова впадина 2",
  "description": "Здесь всё началось и всё заканчивается",
  "postDate": "2023-26-01T08:45:40.284Z",
  "city": "Amsterda",
  "previewImage": "dada.png",
  "photos": [
    "dada1.png",
    "dada2.png",
    "dada3.png",
    "dada4.png",
    "dada5.png",
    "dada6.png"
  ],
  "premiumFlag": false,
  "rating": [
    6.55
  ],
  "type": "apartment",
  "rooms": 1,
  "guests": 1,
  "price": 100000000,
  "comforts": [
    "Washer"
  ],
  "coordinates": {
    "latitude": "52.370216",
    "longitude": "3334.895168"
  },
  "userId": "646a757820ae59d34060494b"
}

###
# Редактирование предложения
PATCH http://localhost:3000/offers/646a76c7c0b4d0ec9275092d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhc3lwQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ3YTk0ZTg5NTIxOTc4YTYzNDAyNGY4IiwidHlwZSI6InBybyIsImlhdCI6MTY4NjA5MjQwNSwiZXhwIjoxNjg2MjY1MjA1fQ.VSyQ_1_21s27J8TDEaGRGCgyI_ueUXaGyCgQ1ZXTA74
Content-Type: application/json

{
  "title": "UPD Хрущевка в центре",
  "description": "UPD Отличный вариант для тех, кто хочет жить в центре и не переплачивать",
  "coordinates": {
    "latitude": "52.370216",
    "longitude": "4.895168"
  },
  "rating": 5
}

###
# Удаление предложения
DELETE http://localhost:3000/offers/646a757820ae59d34060494d HTTP/1.1

###
# Получение детальной информации о предложении
GET http://localhost:3000/offers/646a76c7c0b4d0ec92750d2d HTTP/1.1

###

## Список комментариев к предложению
GET http://localhost:3000/offers/646a76c7c0b4d0ec9275092d/comments?limit=3 HTTP/1.1

###
## Загрузка превью для предложения
POST http://localhost:4000/offers/628a27d729c45f2bf9f6806a/previewImage HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="previewImage"; filename="previewImage.png"
Content-Type: image/png

< C:\Users\moyam\Downloads\previewImage.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###