# Добавление комментария для предложения
POST http://localhost:3000/comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhc3lwQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ3YTk0ZTg5NTIxOTc4YTYzNDAyNGY4IiwidHlwZSI6InBybyIsImlhdCI6MTY4Njk1MjA4OSwiZXhwIjoxNjg3MTI0ODg5fQ.7FI3xlHPokoIZoy0St_WJD9RCxBKvENu65qjkiyDWAc
Content-Type: application/json

{
  "text": "Странное предложение new",
  "offerId": "646a76c7c0b4d0ec9275092d",
  "rating": 4
}
###