# Регистрация нового пользователя
POST http://localhost:3000/users/register HTTP/1.1
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhc3l5QG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4Y2U3ZDdkMGEwMWI5MGVkZTI4YTg0IiwidHlwZSI6InBybyIsImlhdCI6MTY4Njk1NjAxMSwiZXhwIjoxNjg3MTI4ODExfQ.usawfz-x7GWluPADl-A6BkhwvJKEaUtCoJ9I9fR9vnc
Content-Type: application/json

{
  "email": "vasyyk@overlook.net",
  "name": "Вася Уткин",
  "password": "shiggh",
  "type": "pro"
}

###
# Авторизация пользователя
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "vasyy@overlook.net",
  "password": "shiggh"
}

###
# Проверка состояния пользователя
GET http://localhost:3000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhc3l5QG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4Y2U3ZDdkMGEwMWI5MGVkZTI4YTg0IiwidHlwZSI6InBybyIsImlhdCI6MTY4Njk1NzU5MywiZXhwIjoxNjg3MTMwMzkzfQ.oGaXIOjQqKbhWlg5SGc33KvVVOqgyiN0iZXzhTulj2U

###
# Отправка аватарки пользователю
POST http://localhost:3000/users/646a757820ae59d340604946/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhc3l5QG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4Y2U3ZDdkMGEwMWI5MGVkZTI4YTg0IiwidHlwZSI6InBybyIsImlhdCI6MTY4Njk1NzkwNywiZXhwIjoxNjg3MTMwNzA3fQ.uasPLcrmsWS-pfu1frG1Np_G2as31b0Kk3ZYJNMmwXg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="1.css"
Content-Type: text/css

< C:\Users\moyam\Downloads\1.css
------WebKitFormBoundary7MA4YWxkTrZu0gW--