# Создание нового пользователя
POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "vasyp@overlook.net",
  "name": "Вася Пупкин",
  "password": "shiggh",
  "type": "pro"
}

###
# Вход в закрытую часть приложения

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "vasyp@overlook.net",
  "password": "shiggh"
}

###
# Проверка состояния пользователя
GET http://localhost:3000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhc3lwQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ3YTk0ZTg5NTIxOTc4YTYzNDAyNGY4IiwidHlwZSI6InBybyIsImlhdCI6MTY4NjA5MjQwNSwiZXhwIjoxNjg2MjY1MjA1fQ.VSyQ_1_21s27J8TDEaGRGCgyI_ueUXaGyCgQ1ZXTA74
###

## Отправка аватарки пользователю

POST http://localhost:3000/users/646a757820ae59d340604946/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\moyam\Downloads\avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--